### ISSUE TITLE
time slot is not displayed correctly

### ISSUE THREAD

**Issue by satyan01** [TECLIB/fusioninventory-for-glpi#15]
Impossible to change date
Uncaught ReferenceError: d3 is not defined
![image](https://cloud.githubusercontent.com/assets/15144026/16338358/6d927d30-3a1c-11e6-98d9-474641fc9616.png)

**Comment by orthagh** [comment]
hello @satyan01 

Have you downloaded the version provided by this repository ?
a link : https://github.com/orthagh/fusioninventory-for-glpi/archive/0.90/teclib.zip

It's a fork of the official release where we tests new features before submitting them

**Comment by satyan01** [comment]
yes

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/16340290/9aad7814-3a27-11e6-9a47-cb7516822b4a.png)

**Comment by satyan01** [comment]
Operating system: Windows NT UNGSRVGVA218 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) i586
PHP 7.0.4 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, fileinfo, filter, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl,
	pcre, pdo_sqlite, session, soap, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="500M" 
Software: Microsoft-IIS/8.5
	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.1.12-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@ungsrvgva218/glpi91
	Host info: ungsrvgva218 via TCP/IP
	
OKC:\inetpub\wwwroot\glpi91/config : OK
OKC:\inetpub\wwwroot\glpi91/files : OK
OKC:\inetpub\wwwroot\glpi91/files/_dumps : OK
OKC:\inetpub\wwwroot\glpi91/files/_sessions : OK
OKC:\inetpub\wwwroot\glpi91/files/_cron : OK
OKC:\inetpub\wwwroot\glpi91/files/_graphs : OK
OKC:\inetpub\wwwroot\glpi91/files/_lock : OK
OKC:\inetpub\wwwroot\glpi91/files/_plugins : OK
OKC:\inetpub\wwwroot\glpi91/files/_tmp : OK
OKC:\inetpub\wwwroot\glpi91/files/_rss : OK
OKC:\inetpub\wwwroot\glpi91/files/_uploads : OK
OKC:\inetpub\wwwroot\glpi91/files/_pictures : OK
OKC:\inetpub\wwwroot\glpi91/files/_log : OK

**Comment by satyan01** [comment]
Hello, do you have news ?

**Comment by orthagh** [comment]
No. I fail to replicate the issue.
It seems the D3 lib is not loaded on your side, and i don't explain why.

In my case, the lib is well loaded : 
![image](https://cloud.githubusercontent.com/assets/418844/16723546/e4dfb4c8-474d-11e6-964d-6e51c002135a.png)

Could you check your .log files (php and sql), you may have some errors before who before lib loading

**Comment by satyan01** [comment]
maybe it is a clue 

http://stackoverflow.com/questions/25291823/uncaught-referenceerror-d3-is-not-defined

**Comment by orthagh** [comment]
No, the plugin ships this lib, we usually doesn't support cdn (glpi is mainly an intranet software)

**Comment by satyan01** [comment]
I am disappointed, I can't inventory my network it is very annoying

**Comment by ajsb85** [comment]
Open the **WebInspector** and **record a CPU profile** and the **networkt activity**.
Share with us the file .har and .cpuprofile.

**Comment by satyan01** [comment]
attached

**Comment by ajsb85** [comment]
You copy and create a gist:
https://gist.github.com/

**Comment by satyan01** [comment]
I don't understand how to do it and What do you want that I do. Sorry

**Comment by satyan01** [comment]
Hello

Etant Français, parlons français c’est plus simple.

Malheureusement rien dans les log indiquant cela

A disposition si besoin

Yannick

[Unigestion's logo]<http://www.unigestion.com/>



Yannick Labbé
IT Service Desk & IT Training
IT

Unigestion SA
8c, avenue de Champel CP 387
CH 1211 Genève 12



Dir.  +41 (0) 22 704 44 46

Tel.  +41 (0) 22 704 41 11



Fax. +41 (0) 22 704 43 84

Fax. +41 (0) 22 704 42 11



ylabbe@unigestion.com<mailto:ylabbe@unigestion.com>

www.unigestion.com<http://www.unigestion.com>







[LinkedIn logo]  Follow Unigestion on LinkedIn.<http://www.linkedin.com/company/unigestion>







[Awards]<https://www.unigestion.com/awards>

**Comment by orthagh** [comment]
@satyan01, @ajsb85 is not french :)

**Comment by satyan01** [comment]
Hello

No error in php or sql log about that.

Yannick


[Unigestion's logo]<http://www.unigestion.com/>



Yannick Labbé
IT Service Desk & IT Training
IT

Unigestion SA
8c, avenue de Champel CP 387
CH 1211 Genève 12



Dir.  +41 (0) 22 704 44 46

Tel.  +41 (0) 22 704 41 11



Fax. +41 (0) 22 704 43 84

Fax. +41 (0) 22 704 42 11



ylabbe@unigestion.com<mailto:ylabbe@unigestion.com>

www.unigestion.com<http://www.unigestion.com>







[LinkedIn logo]  Follow Unigestion on LinkedIn.<http://www.linkedin.com/company/unigestion>







[Awards]<https://www.unigestion.com/awards>

**Comment by satyan01** [comment]
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1802

Fixed
